function tests = test_mesh
    % Run all function tests in this file
    tests = functiontests(localfunctions);
end


function test_mesh_unconnected_vertices_warning_1d(t)
    % Check that constructing mesh with unconnected vertices emits warning

    dim = 1;
    vertices = [ ...
        0, 1, 2, 3, 4; ...
    ];
    cells = uint32([ ...
        1; ...
        2; ...
    ]);

    verifyWarning(t, @() meshing.Mesh(dim, vertices, cells), 'Mesh:UnconnectedVertices');

end


function test_mesh_unconnected_vertices_warning_2d(t)
    % Check that constructing mesh with unconnected vertices emits warning

    dim = 2;
    vertices = [
        0, 1, 0, 3, 1, 1; ...
        0, 0, 1, 3, 2, 1; ...
    ];
    cells = uint32([ ...
        1, 1; ...
        2, 2; ...
        3, 6; ...
    ]);

    verifyWarning(t, @() meshing.Mesh(dim, vertices, cells), 'Mesh:UnconnectedVertices');

end


function test_mesh_unconnected_vertices_warning_3d(t)
    % Check that constructing mesh with unconnected vertices emits warning

    dim = 3;
    vertices = [
        0, 1, 0, 0, 3, 1, 1; ...
        0, 0, 1, 0, 3, 2, 1; ...
        0, 0, 0, 1, 3, 2, 1; ...
    ];
    cells = uint32([ ...
        1, 1; ...
        2, 2; ...
        3, 3; ...
        4, 6; ...
    ]);

    verifyWarning(t, @() meshing.Mesh(dim, vertices, cells), 'Mesh:UnconnectedVertices');

end
